
##################################################################
#################### JACKDAW KEY BINDINGS ########################
##################################################################


# This file describes Jackdaw's default key bindings.
# Custom bindings will be stored elsewhere.
# If you edit this file, it is likely that things will break.


# format is as follows:

# - [mode name]
#   - [Input str] : [Fn ID]
#   - [Input str] : [Fn ID]
#   ...
# - [mode name]
#   - [Input str] : [Fn ID]
#   ...



---
- global:
  - C-m		: menu
  - C-h		: menu
  - <esc>	: escape
  - C-q		: quit
  - C-z		: undo
  - C-y		: redo
  - C-S-z	: redo
  - C-s		: save_project
  - C-o		: open_file
  - A-S-<del>	: chaotic_user_test
  - C-S-p	: start_api_server
  - <spc>	: function_lookup
- menu_nav:
  - n		: menu_next_item
  - p		: menu_previous_item
  - <tab>	: menu_next_item
  - S-<tab>	: menu_previous_item
  - f		: menu_next_item
  - d		: menu_previous_item
  - <up>	: menu_translate_up
  - <down>	: menu_translate_down
  - <left>	: menu_translate_left
  - <right>	: menu_translate_right
  - <ret>     	: menu_choose_item
  - k		: menu_choose_item
  - <del>     	: menu_dismiss
  - C-n	      	: menu_next_section
  - C-p	      	: menu_previous_section
  - C-f		: menu_next_section
  - C-d		: menu_previous_section
  - C-<up>  	: menu_next_section
  - C-<down>   	: menu_previous_section
  - l	      	: menu_column_right
  - j	      	: menu_column_left
  - m		: menu_dismiss
  - h		: menu_dismiss
  - <esc>	: menu_dismiss
  - g		: menu_dismiss
- timeline:
  - l		: tl_play
  - k		: tl_pause
  - j		: tl_rewind
  - e		: tl_play
  - w		: tl_pause
  - q		: tl_rewind
  - K-l		: tl_play_slow
  - K-j		: tl_rewind_slow
  - S-k		: tl_pause
  - [		: tl_move_playhead_left
  - ]		: tl_move_playhead_right
  - S-[		: tl_move_playhead_left_slow
  - S-]		: tl_move_playhead_right_slow
  - <left>	: tl_nudge_left
  - <right>	: tl_nudge_right
  - S-<left>	: tl_small_nudge_left
  - S-<right>	: tl_small_nudge_right
  - C-S-<left>	: tl_one_sample_left
  - C-S-<right>	: tl_one_sample_right
  - C-k		: tl_toggle_drag
  - S-c		: tl_cut_clipref
  - ;		: tl_move_right
  - h		: tl_move_left
  - ,		: tl_zoom_out
  - .		: tl_zoom_in
  - i		: tl_set_in_mark
  - o		: tl_set_out_mark
  - S-i		: tl_goto_in_mark
  - S-o		: tl_goto_out_mark
  - S-u		: tl_goto_zero
  - S-j		: tl_goto_previous_clip_boundary
  - S-l		: tl_goto_next_clip_boundary
  - C-l		: tl_goto_next_beat
  - C-j		: tl_goto_prev_beat
  - C-S-l	: tl_goto_next_subdiv
  - C-S-j	: tl_goto_prev_subdiv
  - A-S-l	: tl_goto_next_measure
  - A-S-j	: tl_goto_prev_measure
  - S-z		: tl_bring_rear_clip_to_front
  - C-8		: tl_toggle_loop_playback
  - C-S-o	: tl_set_default_out
  - C-t		: tl_track_add
  - 1		: tl_track_select_1
  - 2		: tl_track_select_2
  - 3		: tl_track_select_3
  - 4		: tl_track_select_4
  - 5		: tl_track_select_5
  - 6		: tl_track_select_6
  - 7		: tl_track_select_7
  - 8		: tl_track_select_8
  - 9		: tl_track_select_9
  - `		: tl_track_activate_all
  - n		: tl_track_selector_down
  - p		: tl_track_selector_up
  - <down>	: tl_track_selector_down
  - <up>	: tl_track_selector_up
  - f		: tl_track_selector_down
  - d		: tl_track_selector_up
  - S-n		: tl_move_track_down
  - S-p		: tl_move_track_up
  - S-f		: tl_move_track_down
  - S-d		: tl_move_track_up
  - S-<down>	: tl_move_track_down
  - S-<up>	: tl_move_track_up
  - -		: tl_track_or_tracks_minimize
  - <ret>	: tl_track_activate_selected
  - C-r		: tl_track_rename
  - C-S-i	: tl_track_set_in
  - C-S-m	: tl_track_set_midi_out
  - C-<del>	: tl_track_delete
  - S-t		: tl_track_open_settings
  - S-e		: tl_track_add_effect
  - S-s		: tl_track_open_synth
  - a		: tl_track_show_hide_automations
  - C-a		: tl_track_add_automation
  - S-r		: tl_track_automation_toggle_read
  - <del>	: tl_delete_generic
  - m		: tl_mute
  - s		: tl_solo
  - g		: tl_grab_clips_at_cursor
  - S-g		: tl_grab_marked_range
  - C-c		: tl_copy_grabbed_clips
  - C-v		: tl_paste_grabbed_clips
  - C-S-r	: tl_rename_clip_at_cursor
  - r		: tl_record
  - C-S-t	: tl_click_track_add
  - t		: tl_click_track_set_tempo
  - C-1		: tl_load_clip_at_cursor_to_source
  - S-1		: tl_activate_source_mode
  - b		: tl_drop_from_source
  - v		: tl_drop_saved1_from_source
  - c		: tl_drop_saved2_from_source
  - x		: tl_drop_saved3_from_source
  - z		: tl_drop_saved4_from_source
  - S-=		: tl_track_vol_up
  - S--		: tl_track_vol_down
  - S-9		: tl_track_pan_left
  - S-0		: tl_track_pan_right
  - A-t		: tl_add_new_timeline
  - A-j		: tl_previous_timeline
  - A-l		: tl_next_timeline
  - A-<del>	: tl_delete_timeline
  - C-e		: tl_write_mixdown_to_wav
  - S-w		: tl_write_mixdown_to_wav
- source:
  - l		: source_play
  - k		: source_pause
  - j		: source_rewind
  - S-l		: source_play_slow
  - S-j		: source_rewind_slow
  - S-k		: source_pause
  - K-l		: source_play_slow
  - K-j		: source_rewind_slow
  - i		: source_set_in_mark
  - o		: source_set_out_mark
  - S-i		: source_set_in_mark
  - S-o		: source_set_out_mark
  - ,		: source_zoom_out
  - .		: source_zoom_in
  - h		: source_move_left
  - ;		: source_move_right
- modal:
  - n		: modal_next
  - p		: modal_previous
  - f		: modal_next
  - d		: modal_previous
  - <down>	: modal_next
  - <up>	: modal_previous
  - <tab>	: modal_next_escape
  - S-<tab>	: modal_previous_escape
  - S-n		: modal_next_escape
  - S-p		: modal_previous_escape
  - S-f		: modal_next_escape
  - S-d		: modal_previous_escape
  - S-<down>	: modal_next_escape
  - S-<up>	: modal_previous_escape
  - <ret>	: modal_select
  - m		: modal_dismiss
  - h		: modal_dismiss
  - g		: modal_dismiss
  - <esc>	: modal_dismiss
  - C-<ret>	: modal_submit_form
- text_edit:
  - <ret>	: text_edit_escape
  - <tab>	: text_edit_escape
  - <esc>	: text_edit_full_escape
  - S-<tab>	: text_edit_escape
  - <del>	: text_edit_backspace
  - <left>	: text_edit_cursor_left
  - <right>	: text_edit_cursor_right
  - C-d		: text_edit_cursor_left
  - C-b		: text_edit_cursor_left
  - C-f		: text_edit_cursor_right
  - C-a		: text_edit_select_all
- tabview:
  - S-n		: tabview_next_escape
  - S-p		: tabview_previous_escape
  - S-<down>	: tabview_next_escape
  - S-<up>	: tabview_previous_escape
  - S-f		: tabview_next_escape
  - S-d		: tabview_previous_escape
  - <tab>	: tabview_next_escape
  - S-<tab>	: tabview_previous_escape
  - <ret>	: tabview_enter
  - h		: tabview_left
  - ;		: tabview_right
  - S-j		: tabview_previous_tab
  - S-h		: tabview_previous_tab
  - S-l		: tabview_next_tab
  - S-;		: tabview_next_tab
  - C-S-j	: tabview_move_current_tab_left
  - C-S-l	: tabview_move_current_tab_right
  - C-S-h	: tabview_move_current_tab_left
  - C-S-;	: tabview_move_current_tab_right
  - g		: tabview_escape
  - <esc>	: tabview_escape
- autocomplete_list:
  - <tab>	: autocomplete_next
  - S-<tab>	: autocomplete_previous
  - <down>	: autocomplete_next
  - <up>	: autocomplete_previous
  - C-n		: autocomplete_next
  - C-p		: autocomplete_previous
  - <ret>	: autocomplete_select
  - <esc>	: autocomplete_escape
- midi_qwerty:
  - z		: midi_qwerty_octave_down
  - x		: midi_qwerty_octave_up
  - ,		: midi_qwerty_transpose_down
  - .		: midi_qwerty_transpose_up
  - a		: midi_qwerty_c1
  - w		: midi_qwerty_cis1
  - s		: midi_qwerty_d1
  - e		: midi_qwerty_dis
  - d		: midi_qwerty_e
  - f		: midi_qwerty_f
  - t		: midi_qwerty_fis
  - g		: midi_qwerty_g
  - y		: midi_qwerty_gis
  - h		: midi_qwerty_a
  - u		: midi_qwerty_ais
  - j		: midi_qwerty_b
  - k		: midi_qwerty_c2
  - o		: midi_qwerty_cis2
  - l		: midi_qwerty_d2
  - p		: midi_qwerty_dis2
  - ;		: midi_qwerty_e2
  - '		: midi_qwerty_f2
  - i		: null
  - q		: null
  - r		: null
  - <ret>	: null
  - [		: null
  - ]		: null
  - <esc>	: midi_qwerty_escape