#ifndef JDAW_GUI_EVENT_STATE_H
#define JDAW_GUI_EVENT_STATE_H

#define E_STATE_QUIT 0x01
#define E_STATE_SHIFT 0x02
#define E_STATE_CMDCTRL 0x04
#define E_STATE_MOUSE_L 0x08
#define E_STATE_MOUSE_R 0x10
#define E_STATE_MOUSE_M 0x20

#endif
